#!/bin/bash

wget -nv https://repo1.maven.org/maven2/org/apache/hive/hive-metastore/1.1.1/hive-metastore-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/hive-exec/1.1.1/hive-exec-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/hive-common/1.1.1/hive-common-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/hive-serde/1.1.1/hive-serde-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/com/google/guava/guava/14.0.1/guava-14.0.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/2.7.4/hadoop-client-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/hive-shims/1.1.1/hive-shims-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/com/jolbox/bonecp/0.8.0.RELEASE/bonecp-0.8.0.RELEASE.jar 
wget -nv https://repo1.maven.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.jar 
wget -nv https://repo1.maven.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar 
wget -nv https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/derby/derby/10.11.1.1/derby-10.11.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/datanucleus/datanucleus-api-jdo/3.2.6/datanucleus-api-jdo-3.2.6.jar 
wget -nv https://repo1.maven.org/maven2/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10.jar 
wget -nv https://repo1.maven.org/maven2/org/datanucleus/datanucleus-rdbms/3.2.9/datanucleus-rdbms-3.2.9.jar 
wget -nv https://repo1.maven.org/maven2/commons-pool/commons-pool/1.5.4/commons-pool-1.5.4.jar 
wget -nv https://repo1.maven.org/maven2/commons-dbcp/commons-dbcp/1.4/commons-dbcp-1.4.jar 
wget -nv https://repo1.maven.org/maven2/javax/jdo/jdo-api/3.0.1/jdo-api-3.0.1.jar 
wget -nv https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.4/antlr-runtime-3.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/thrift/libfb303/0.9.2/libfb303-0.9.2.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar 
wget -nv https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar 
wget -nv https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/avro/avro/1.7.5/avro-1.7.5.jar 
wget -nv https://repo1.maven.org/maven2/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar 
wget -nv https://repo1.maven.org/maven2/com/twitter/parquet-hadoop-bundle/1.6.0rc3/parquet-hadoop-bundle-1.6.0rc3.jar 
wget -nv https://repo1.maven.org/maven2/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.1/ant-1.9.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/shims/hive-shims-common/1.1.1/hive-shims-common-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar 
wget -nv https://repo1.maven.org/maven2/jline/jline/2.12/jline-2.12.jar 
wget -nv https://repo1.maven.org/maven2/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/shims/hive-shims-0.20S/1.1.1/hive-shims-0.20S-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/shims/hive-shims-0.23/1.1.1/hive-shims-0.23-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/shims/hive-shims-scheduler/1.1.1/hive-shims-scheduler-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-resourcemanager/2.6.0/hadoop-yarn-server-resourcemanager-2.6.0.jar 
wget -nv https://repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/3.0/guice-servlet-3.0.jar 
wget -nv https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar 
wget -nv https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar 
wget -nv https://repo1.maven.org/maven2/com/google/inject/guice/3.0/guice-3.0.jar 
wget -nv https://repo1.maven.org/maven2/com/sun/jersey/jersey-json/1.14/jersey-json-1.14.jar 
wget -nv https://repo1.maven.org/maven2/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar 
wget -nv https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar 
wget -nv https://repo1.maven.org/maven2/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar 
wget -nv https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.14/jersey-core-1.14.jar 
wget -nv https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar 
wget -nv https://repo1.maven.org/maven2/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-applicationhistoryservice/2.6.0/hadoop-yarn-server-applicationhistoryservice-2.6.0.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-web-proxy/2.6.0/hadoop-yarn-server-web-proxy-2.6.0.jar 
wget -nv https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar 
wget -nv https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar 
wget -nv https://repo1.maven.org/maven2/org/sonatype/sisu/inject/cglib/2.2.1-v20090111/cglib-2.2.1-v20090111.jar 
wget -nv https://repo1.maven.org/maven2/asm/asm/3.2/asm-3.2.jar 
wget -nv https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar 
wget -nv https://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar 
wget -nv https://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.jar 
wget -nv https://repo1.maven.org/maven2/com/sun/jersey/jersey-server/1.14/jersey-server-1.14.jar 
wget -nv https://repo1.maven.org/maven2/org/tukaani/xz/1.0/xz-1.0.jar 
wget -nv https://repo1.maven.org/maven2/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.jar 
wget -nv https://repo1.maven.org/maven2/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.1/ant-launcher-1.9.1.jar 
wget -nv https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar 
wget -nv https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.5/snappy-java-1.0.5.jar 
wget -nv https://repo1.maven.org/maven2/javax/transaction/jta/1.1/jta-1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar 
wget -nv https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hive/hive-ant/1.1.1/hive-ant-1.1.1.jar 
wget -nv https://repo1.maven.org/maven2/org/antlr/ST4/4.0.4/ST4-4.0.4.jar 
wget -nv https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.1.6/groovy-all-2.1.6.jar 
wget -nv https://repo1.maven.org/maven2/stax/stax-api/1.0.1/stax-api-1.0.1.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/velocity/velocity/1.5/velocity-1.5.jar 
wget -nv https://repo1.maven.org/maven2/oro/oro/2.0.8/oro-2.0.8.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/2.7.4/hadoop-common-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/2.7.4/hadoop-hdfs-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-app/2.7.4/hadoop-mapreduce-client-app-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-api/2.7.4/hadoop-yarn-api-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.4/hadoop-mapreduce-client-core-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.7.4/hadoop-mapreduce-client-jobclient-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-annotations/2.7.4/hadoop-annotations-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.1.1/commons-math3-3.1.1.jar 
wget -nv https://repo1.maven.org/maven2/xmlenc/xmlenc/0.52/xmlenc-0.52.jar 
wget -nv https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar 
wget -nv https://repo1.maven.org/maven2/commons-net/commons-net/3.1/commons-net-3.1.jar 
wget -nv https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar 
wget -nv https://repo1.maven.org/maven2/org/mortbay/jetty/jetty-sslengine/6.1.26/jetty-sslengine-6.1.26.jar 
wget -nv https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar 
wget -nv https://repo1.maven.org/maven2/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar 
wget -nv https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar 
wget -nv https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar 
wget -nv https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar 
wget -nv https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-auth/2.7.4/hadoop-auth-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/htrace/htrace-core/3.1.0-incubating/htrace-core-3.1.0-incubating.jar 
wget -nv https://repo1.maven.org/maven2/commons-digester/commons-digester/1.8/commons-digester-1.8.jar 
wget -nv https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar 
wget -nv https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar 
wget -nv https://repo1.maven.org/maven2/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar 
wget -nv https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar 
wget -nv https://repo1.maven.org/maven2/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar 
wget -nv https://repo1.maven.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar 
wget -nv https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-common/2.7.4/hadoop-mapreduce-client-common-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-shuffle/2.7.4/hadoop-mapreduce-client-shuffle-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-common/2.7.4/hadoop-yarn-common-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-client/2.7.4/hadoop-yarn-client-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-common/2.7.4/hadoop-yarn-server-common-2.7.4.jar 
wget -nv https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-jaxrs/1.9.13/jackson-jaxrs-1.9.13.jar 
wget -nv https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-xc/1.9.13/jackson-xc-1.9.13.jar
mkdir /opt/spark/hive_1.1.0_jars
mv *.jar /opt/spark/hive_1.1.0_jars/