FROM dataiku/dss:8.0.2

USER root

# Nginx
#RUN apt-get update \
#  && apt-get install -y nginx \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/
#
#
#RUN rm /etc/nginx/sites-enabled/default
#
#EXPOSE 10000
#ADD resources/entrypoint.sh /entrypoint.sh
#ENTRYPOINT ["/entrypoint.sh"]
#
#CMD ["/bin/sh", "-c", "/init_rstudio.sh"]
