version: v1
type: APP
id: grafana
label: Grafana
baseline: "Grafana is an open-source data visualization platform for monitoring and observability."
description: "Grafana is a visualization and dashboard platform that allows you to query, visualize, alert on, and understand your metrics, logs, and traces no matter where they are stored."
available: true
icon: grafana
defaultResources: 
  cpu: 
    limit: 1
  memory:
    limit: 2 GiB
backgroundColor: "#1857B8"
customFlags: []
readme: /technologies/app/grafana