version: v1
type: APP
id: grafana
label: Grafana
baseline: The open-source platform for monitoring and observability. Default admin login is `admin`. Default admin password must be set with the GRAFANA_ADMIN_PASSWORD environment variable.
description: Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored.
available: true
icon: grafana
backgroundColor: "#1857B8"
customFlags: []
readme: /technologies/app/grafana