id: grafana-8.2
label: 8.2
releaseNotes: First version of Grafana 8.2 into Saagie.
available: true
trustLevel: stable
ports:
  - port: 80
    name: Grafana
    rewriteUrl: false
    basePath: GF_SERVER_DOMAIN
volumes: ["/opt/grafana", "/opt/plugins"]
