# This is a deprecated image which will ne longer be maintained by Saagie. Moreover the original Dockerfile
# can no longer be built as is. Therefore this Dockerfile will just reference the original Docker image last built on Jan 6th 2021

FROM saagie/jupyter-python-nbk:pyspark-1.73.0

