#!/bin/sh
#pwd
#ls -al

sed -i 's:SAAGIE_BASE_PATH:'"$SAAGIE_BASE_PATH"':g' /etc/nginx/sites-enabled/toucan.conf

docker login -u $DOCKER_USER -p $DOCKER_PASSWD
docker-compose build
docker-compose pull

docker-compose up -d

# Trick to keep container up
# if used this means "parent" container will keep running
# so you'll need to connect to it to reach "child" containers
# if kept commented, "child" containes will be reachable from host directly
#CMD tail -f /dev/null

nginx