# This is a deprecated image which will ne longer be maintained by Saagie. Moreover the original Dockerfile
# can no longer be built as is. Therefore this Dockerfile will just reference the original Docker image
FROM saagie/jupyter-python-nbk:v2-minimal-1.63.0
