{
 "title": "Saagie - Job Count",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total # of Jobs and Apps on Saagie",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(job_count)\nFROM supervision_saagie_jobs_snapshot\nwhere snapshot_date = (select MAX(snapshot_date) FROM supervision_saagie_jobs_snapshot )"
    }
   ]
  },
  {
   "title": "Per project",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  project_name as \"metric\",\n  job_count AS \"value\"\nFROM supervision_saagie_jobs_snapshot\nwhere snapshot_date = (select MAX(snapshot_date) FROM supervision_saagie_jobs_snapshot )\nGROUP BY project_name,job_count\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Job/App evolution",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_date,$__interval),\n  project_name AS metric,\n  sum(job_count) AS \"job_count\"\nFROM supervision_saagie_jobs_snapshot\nWHERE\n  $__timeFilter(snapshot_date)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Job details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  project_name as \"Project\",\n  orchestration_name as \"Name\",\n  technology as \"Technology\",\n  orchestration_category as \"Category\",\n  creation_date as \"Creation Date\",\n  instance_count as \"# of instances\"\n  FROM supervision_saagie_jobs\n  ORDER BY 1,2,3 ASC\n"
    }
   ]
  },
  {
   "title": "App details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  project_name as \"Project\",\n  orchestration_name as \"Name\",\n  technology as \"Technology\",\n  current_status as \"Current Status\",\n  creation_date as \"Creation Date\",\n  start_time as \"Start Time\",\n  stop_time as \"Stop Time\"\n  \nFROM supervision_saagie_apps\nORDER BY 1,2,3"
    }
   ]
  }
 ]
}