id: grafana-9.2
label: "9.2"
releaseNotes: First version of Grafana 9.2 into Saagie.
available: true
trustLevel: stable
recommended: true
ports:
  - port: 80
    name: Grafana
    rewriteUrl: false
    basePath: GF_SERVER_DOMAIN
volumes: ["/opt/grafana", "/opt/plugins"]
