{
 "title": "Saagie - Pipelines & Jobs Executions",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project",
    "label": "Project",
    "query": "SELECT DISTINCT project_name\nFROM supervision_saagie_jobs\nORDER BY 1"
   }
  ]
 },
 "panels": [
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs Failed / Killed Timeline",
   "type": "timeseries",
   "description": "Jobs Failed  in red \nJobs Killed in yellow",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  instance_end_time AS \"time\",\n  instance_duration as value,\n  project_name || ' - '|| orchestration_name || ' - '|| instance_status  as metric,\n  instance_saagie_url\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='job'\n  and instance_status='FAILED'\n  and project_name in (${Project})\n  order by time"
    },
    {
     "rawSql": "SELECT\n  instance_end_time AS \"time\",\n  instance_duration as value,\n  project_name || ' - '|| orchestration_name || ' - '|| instance_status  as metric,\n  instance_saagie_url\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='job'\n  and instance_status='KILLED'\n  and project_name in (${Project})\n  order by time"
    }
   ]
  },
  {
   "title": "Jobs Timeline",
   "type": "state-timeline",
   "description": "Jobs Failed  in red \nJobs Killed in yellow",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  instance_start_time AS \"time\",\n  project_name || ' - '|| orchestration_name  as metric,\n  instance_status as \" \"\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='job'\n  and project_name in (${Project})\nUNION ALL\nSELECT\n  instance_end_time AS \"time\",\n  project_name || ' - '|| orchestration_name  as metric,\n  null as \" \"\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='job'\n  and project_name in (${Project})\n  order by metric\n"
    }
   ]
  },
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Pipelines Failed / Killed Timeline",
   "type": "timeseries",
   "description": "Pipelines Failed  in red \nPipelines Killed in yellow",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  instance_end_time AS \"time\",\n  instance_duration as value,\n  project_name || ' - '|| orchestration_name || ' - '|| instance_status  as metric,\n  instance_saagie_url\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='pipeline'\n  and instance_status='FAILED'\n  and project_name in (${Project})\n  order by time"
    },
    {
     "rawSql": "SELECT\n  instance_end_time AS \"time\",\n  instance_duration as value,\n  project_name || ' - '|| orchestration_name || ' - '|| instance_status  as metric,\n  instance_saagie_url\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='pipeline'\n  and instance_status='KILLED'\n  and project_name in (${Project})\n  order by time"
    }
   ]
  },
  {
   "title": "Pipelines Timeline",
   "type": "state-timeline",
   "description": "Pipelines Failed  in red \nPipelines Killed in yellow",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  instance_start_time AS \"time\",\n  project_name || ' - '|| orchestration_name  as metric,\n  instance_status as \" \"\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='pipeline'\n  and project_name in (${Project})\nUNION ALL\nSELECT\n  instance_end_time AS \"time\",\n  project_name || ' - '|| orchestration_name  as metric,\n  null as \" \"\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_end_time)\n  and orchestration_type='pipeline'\n  and project_name in (${Project})\n  order by metric\n"
    }
   ]
  }
 ]
}