{
 "title": "Data Lake - Global Usage",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Folder size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT supervision_date as time, \n\tsubstring(supervision_label, position('/' in supervision_label)) folder,\n\tround(supervision_value/1024/1024/1024) size_in_Gb\n\tFROM supervision_datalake\n\tWHERE supervision_label like 'Data size%' and supervision_label not like '%/data/%'\n\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "File count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT supervision_date as time, \n\tsubstring(supervision_label, position('/' in supervision_label)) folder,\n\tround(supervision_value) file_count\n\tFROM supervision_datalake\n\tWHERE supervision_label like 'File Count%' and supervision_label not like '%/data/%'\n\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Folder size /data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT supervision_date as time, \n\tsubstring(supervision_label, position('/' in supervision_label)) folder,\n\tround(supervision_value/1024/1024/1024) size_in_Gb\n\tFROM supervision_datalake\n\tWHERE supervision_label like 'Data size%' and supervision_label  like '%/data/%'\n\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "File count /data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT supervision_date as time, \n\tsubstring(supervision_label, position('/' in supervision_label)) folder,\n\tround(supervision_value) file_count\n\tFROM supervision_datalake\n\tWHERE supervision_label like 'File Count%' and supervision_label like '%/data/%'\n\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average file size in kb",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT supervision_date AS \"time\",\nsubstring(supervision_label, position('/' in supervision_label)) AS folder,\nround(supervision_value/1024) as value_in_kb\nFROM supervision_datalake\nWHERE supervision_label like 'Average size file%' and supervision_label not like '%/data/%'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average file size in kb /data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT supervision_date AS \"time\",\nsubstring(supervision_label, position('/' in supervision_label)) AS folder,\nround(supervision_value/1024) as value_in_kb\nFROM supervision_datalake\nWHERE supervision_label like 'Average size file%' and supervision_label like '%/data/%'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Data Lake usage over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  supervision_date AS \"time\",\n  supervision_label as \"metric\",\n  supervision_value AS \"value\"\nFROM supervision_datalake\nWHERE\n  $__timeFilter(supervision_date)\n  AND supervision_label in ('total_capacity', 'total_used')\nGROUP BY supervision_date, supervision_label\nORDER BY 1,2"
    }
   ]
  }
 ]
}