#!/bin/bash

# Change default CRAN to ENV VAR if present
if [[ -z "${R_CUSTOM_CRAN}" ]]; then
    echo "No custom CRAN defined, using default, you can configure one using R_CUSTOM_CRAN env var"
else
    sed -i 's#https://cloud.r-project.org#'"${R_CUSTOM_CRAN}"'#g' /usr/lib/R/etc/Rprofile.site
fi

set -euo pipefail
if compgen -G "*.zip*" > /dev/null; then
    echo "Zip file detected ... unzipping ..."
    unzip -qo *.zip
fi
if test -f main_script; then
    echo "'main_script' detected ... executing ..."
    sh ./main_script
else
    exec "$@"
fi