export const JobStatus = {
    AWAITING: 'AWAITING',
    REQUESTED: 'REQUESTED',
    QUEUED: 'QUEUED',
    RUNNING: 'RUNNING',
    SUCCEEDED: 'SUCCEEDED',
    KILLING: 'KILLING',
    KILLED: 'KILLED',
    FAILED: 'FAILED',
};
